# Generated by Django 3.0.2 on 2020-02-06 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qv1', '0002_auto_20200206_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='choice1',
            field=models.TextField(verbose_name='question1'),
        ),
        migrations.AlterField(
            model_name='question',
            name='choice2',
            field=models.TextField(verbose_name='question2'),
        ),
        migrations.AlterField(
            model_name='question',
            name='choice3',
            field=models.TextField(verbose_name='question3'),
        ),
        migrations.AlterField(
            model_name='question',
            name='choice4',
            field=models.TextField(verbose_name='question4'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
