# Generated by Django 3.0.2 on 2020-02-06 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qv1', '0003_auto_20200206_1948'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Person',
        ),
    ]
